version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  NUGETAPIKEY:
    secure: VKjdo0FDOKVVrhJ4zAZ6FTaRcN34YdVbaSloJP+SkJzvhq8BEERYdE/wRt1JV2I6
build_script:
- ps: .\build.ps1
test: off
deploy: off